Create image_resize_test.rs
Holmusk/Rust-ImageResizing-Benchmarks pull request #11
Opened 2020-05-27 10:00 UTC by kriti0111

Test functions for verifying dimensions of the resized image

2020-05-27 10:23 UTC, kahlil29 requested changes
Good first attempt at writing tests for the resizing

2020-05-27 10:23 UTC, kahlil29 commented on tests/image_resize_test.rs
> +    assert_eq!(image_resized.dimensions(), (299,56));
I'm not too sure about this, but would it be a better idea to use the `assert_ne!` function here with the same values as the previous test function?

2020-05-27 10:23 UTC, kahlil29 commented on tests/image_resize_test.rs
> +    let image_resized =   img.resize_exact(299, 299,FilterType:: CatmullRom);
It seems to me that you're testing the library function rather than the function that you've written.
There should be a call to your `resize_image` function here.
It may seem redundant, but that's the purpose of the test. Today your function is just pretty much a call to the `resize_exact` function but things may change over time (not likely in the case of this function) and you would want the tests to catch any mistakes made when refactoring code. 

If you want to make it easier for you to test this, you can change the output of the `resize_img` function to give you an `image` object OR you can convert the `Vec` that you get back into an `image` object and get its dimensions. 
The latter approach may be better as you would not have to change anything once you implement the `upload_to_s3` function.

2020-05-27 10:23 UTC, kahlil29 commented on tests/image_resize_test.rs
> +    let image_resized =   img.resize_exact(299, 299,FilterType:: CatmullRom);
Please replace with call to `resize_image`

2020-05-28 06:56 UTC, kahlil29 commented on src/img_resizing_lambda.rs
>          Ok(scaledimg) => scaledimg,
```suggestion
        Ok(()) => (),
```

2020-05-28 06:56 UTC, kahlil29 commented on src/img_resizing_lambda.rs
>          Ok(scaledimg) => scaledimg,
If I'm not mistaken this returns an `Ok(())` right? So it's a bit misleading to use that variable there.

2020-05-28 06:57 UTC, kahlil29 requested changes
One more small change required 😄

2020-05-28 06:58 UTC, kahlil29 commented on src/test.rs
> +    use image::{imageops::FilterType, ImageBuffer,GenericImageView};
Indentation? 
Did you run the formatter here?

2020-05-28 07:03 UTC, kahlil29 commented
Closes #10

2020-05-28 07:07 UTC, kriti0111 commented on src/test.rs
> +    use image::{imageops::FilterType, ImageBuffer,GenericImageView};
I think the changes are from your last commit. I didn't make any changes to that file.

2020-05-28 07:11 UTC, kahlil29 commented on src/test.rs
> +    use image::{imageops::FilterType, ImageBuffer,GenericImageView};
Oops. You're right. Just ran the formatter over the project and pushed the changes.

2020-05-28 08:41 UTC, merged