resizing images with Image
Holmusk/Rust-ImageResizing-Benchmarks pull request #2
Opened 2020-05-21 07:24 UTC by kriti0111

2020-05-21 07:59 UTC, kahlil29 requested changes
- Let's not commit the `Cargo.lock` file for now as it may be a problem when adding CI 
- Have a folder called `images` where you have 2 sub-directories : 
   1. `original` OR `raw` 
   2. `resized`  
  Also please add some images with some distinct labels e.g. 1, 2, 3, 4, 5 or a,b, c etc
- Please shift this code into `Image_Lib.rs`. 
- The output image should just add a suffix `_resized` to the input image name. e.g. `myImageName123` should become `myImageName123_resized` and it should be written to the `resized` folder.

2020-05-21 11:17 UTC, kahlil29 commented on src/Image_Lib.rs
> +                '.' => break,
I don't fully follow what's happening here. 
You have the filename as a `String`, so is it possible to just do 
`format!("{}{}", filename, "_resized".to_string)`  ?

2020-05-21 11:20 UTC, kriti0111 commented on src/Image_Lib.rs
> +                '.' => break,
I have the filename along with the extension

2020-05-21 11:23 UTC, kahlil29 commented on src/Image_Lib.rs
> +                '.' => break,
If a file `apple.jpg` becomes `apple.jpg_resized`, I don't think it really affects/changes much. 
I could be mistaken though. Can verify manually.

2020-05-21 11:25 UTC, kriti0111 commented on src/Image_Lib.rs
> +                '.' => break,
Oh if we can have that then the problem is solved

2020-05-21 11:29 UTC, kriti0111 commented on src/Image_Lib.rs
> +                '.' => break,
I just checked it. I tried renaming a file as xyz.jpg_resized. It cannot be opened by the default windows app but I was able to open it with the paint app.

2020-05-21 11:30 UTC, kahlil29 commented on src/Image_Lib.rs
> +                '.' => break,
Yeah also going down this route can be a bit of a rabbit hole because I just tried with an image that does not have the extension in the filename (a very valid use-case) and the program crashed 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/Image_Lib.rs:19:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 
Let's make it simple by just appending the `_resized` 👍

2020-05-21 11:36 UTC, kriti0111 commented on src/Image_Lib.rs
> +                '.' => break,
Yeah makes sense. I'll upload the changes

2020-05-21 11:40 UTC, kahlil29 reviewed
For some reason, the resized images are of varying dimensions at times, it seems random. 
I got dimensions of (299 x 199) , (282 x 299), (299 x 149). 
Can you verify? This is really weird and should not be happening 🤔

2020-05-22 03:53 UTC, merged

2020-05-22 04:00 UTC, kriti0111 commented
The function `resize()` in `src/Imagelib.rs` maintains aspect ratio and hence we weren't getting the required dimensions. Changing the function to `resize_exact()` gives us a resized image with the dimensions specified strictly.